/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Form;

import Konstate.Operacije;
import domen.Angazovanje;
import domen.Predmet;
import domen.Profesor;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import transfer.KlijentskiZahtev;


public class AngazovanjeDijalog extends javax.swing.JDialog {
    
    Angazovanje angazovnje;
    SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
    java.awt.Frame parent;
    List<Predmet> predmeti = new ArrayList<>();
    KlijentskaForma kf;

    /**
     * Creates new form Angazovanje
     */
    public AngazovanjeDijalog(java.awt.Frame parent, boolean modal, Angazovanje a, KlijentskaForma kf) throws ParseException {
        super(parent, modal);
        initComponents();
        angazovnje= a;
        this.parent = parent;
        this.kf = kf;
        prepare();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPredmet = new javax.swing.JComboBox<>();
        txtDatum = new javax.swing.JFormattedTextField();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Datum:");

        jLabel2.setText("Predmet:");

        cmbPredmet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDatum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPredmet, 0, 234, Short.MAX_VALUE)
                    .addComponent(txtDatum))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (angazovnje == null){
            Angazovanje a = new Angazovanje();
            try {
                a.setDatumAngazovanja(sdf.parse(txtDatum.getText()));
            a.setPredmet(predmeti.get(cmbPredmet.getSelectedIndex()));
            kf.dodaj(a);
            } catch (ParseException ex) {
                Logger.getLogger(AngazovanjeDijalog.class.getName()).log(Level.SEVERE, null, ex);
                return;
            }
        } else {
            kf.izmeni(angazovnje);
        }
    }//GEN-LAST:event_btnOKActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cmbPredmet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField txtDatum;
    // End of variables declaration//GEN-END:variables

    private void prepare() throws ParseException {
        Kom.Komunikacija.getInstance().posaljiZahtev(new KlijentskiZahtev(Operacije.VRATI_PREDMETE, null));
        //predmeti = (List<Predmet>) Kom.Komunikacija.getInstance().primiOdgovor().getOdgovor();
        Predmet p = new Predmet();
        p.setNaziv("Proj Soft");
        Predmet p1 = new Predmet();
        p1.setNaziv("Programiranje 1");
        Predmet p2 = new Predmet();
        p1.setNaziv("Menadzment");
        predmeti.add(p);
        predmeti.add(p1);
        predmeti.add(p2);
        for (Predmet pr: predmeti){
            cmbPredmet.addItem(pr.getNaziv());
        }
        if (angazovnje != null){;
        }
    }
}
